config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exam.urls')),
]

exam/urls.py
from django.urls import path
from .views import category_view, question_list, quiz_result, QuizListView


app_name = 'exam'
urlpatterns = [
    path('', QuizListView.as_view(), name='quiz_list'),
    path('quiz/<slug:slug>', question_list, name='question_list'),
    path('quiz/<slug:slug>/result', quiz_result, name='quiz_result'),
    path('category/<slug:slug>', category_view, name='category_view'),
]

exam/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

##MANAGER

class QuestionManager(models.Manager):
    def published(self):
        return self.filter(status='p')

class QuizManager(models.Manager):
    def published(self):
        return self.filter(status=True)



# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=100,verbose_name='عنوان')
    slug   = models.SlugField(unique=True, verbose_name='آدرس')
    status = models.BooleanField(default=True, verbose_name='وضعیت انتشار')
    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'
        ordering = ['status']
    def __str__(self):
        return self.title

class Quiz(models.Model):
    title  = models.CharField(max_length=150, verbose_name='عنوان')
    description = models.CharField(max_length=250, verbose_name='توضیحات', blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default = 1, related_name='quiz', verbose_name='نویسنده')
    category = models.ManyToManyField(Category, default=None, blank=True, related_name='quiz', verbose_name='دسته بندی')
    slug   = models.SlugField(unique=True, verbose_name='آدرس')
    publish = models.DateTimeField(default=timezone.now, verbose_name='زمان انتشار')
    status = models.BooleanField(default=True, verbose_name='وضعیت انتشار')
    class Meta:
        verbose_name = 'آزمون'
        verbose_name_plural = 'آزمون ها'
        ordering = ['-publish']
    def __str__(self):
        return self.title

    def category_to_str(self):
        return "، ".join([category.title for category in self.category.all()])
    category_to_str.short_description = 'دسته بندی ها'

    def count_question_publish(self):
        return self.question.filter(status='p').count()
    count_question_publish.short_description = 'تعداد سوالات'

    objects = QuizManager()




class Question(models.Model):
    ANSWER_CHOICES =(
    (1,'یک'),
    (2,'دو'),
    (3,'سه'),
    (4,'چهار'),
    )
    STATUS_CHOICES=(
    ('p','منتشر شده'),
    ('d','پیشنویس'),
    )
    title = models.CharField(max_length=300, verbose_name='عنوان')
    quiz  = models.ManyToManyField(Quiz, related_name='question', verbose_name='آموزن')
    answer_one = models.CharField(max_length=300, verbose_name='گزینه یک')
    answer_two = models.CharField(max_length=300, verbose_name='گزینه دو')
    answer_three = models.CharField(max_length=300, verbose_name='گزینه سه')
    answer_four = models.CharField(max_length=300, verbose_name='گزینه چهار')
    answer_true = models.IntegerField(choices=ANSWER_CHOICES, verbose_name='گزینه صحیح')
    status = models.CharField(max_length=1, default='p', choices=STATUS_CHOICES, verbose_name='وضعیت')
    class Meta:
        verbose_name = 'سوال'
        verbose_name_plural = 'سوالات'
        ordering = ['status']
    def __str__(self):
        return self.title

    def quiz_to_str(self):
        return "، ".join([quiz.title for quiz in self.quiz.all()])
    quiz_to_str.short_description = 'آزمون های'

    objects = QuestionManager()

exam/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.list import ListView
from .models import Question, Quiz, Category


# Create your views here.

class QuizListView(ListView):
    queryset = Quiz.objects.published()



def question_list(request,slug):
    quiz = get_object_or_404(Quiz, slug=slug, status=True)
    questions = quiz.question.published()
    context ={
        'quiz' : quiz,
        'questions' : questions,
    }
    return render(request, 'exam/question_list.html', context)

def quiz_result(request,slug):
    quiz = get_object_or_404(Quiz, slug=slug, status=True)
    if request.method == 'POST':
        number_true_answer = 0
        for question in request.POST:
            if question == 'csrfmiddlewaretoken':
                continue
            if int(request.POST[question]) == int(Question.objects.get(pk=int(question)).answer_true):
                number_true_answer += 1
        context = {
            'number_true_answer': number_true_answer,
            'quiz' : quiz
        }
        return render(request, 'exam/quiz_result.html', context)
    else:
        return redirect(reverse('exam:question_list', args=[slug]))

def category_view(request, slug):
   category = get_object_or_404(Category, slug=slug, status=True)
   quiz_list = category.quiz.filter(status=True)
   context = {
       'category': category,
       'quiz_list': quiz_list,     
   }
   return render(request,'exam/category.html', context)

exam/templates/exam/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'exam/css/master.css' %}">
    <link rel="stylesheet" href="{% static 'exam/css/bootstrap.min.css"' %}">
    <link rel="stylesheet" href="{% static 'exam/css/custom-rtl.min.css' %}">
    <title>آزمون سرا | {% block title %}{% endblock %}</title>
  </head>
<body>

  {% block content %}{% endblock %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdn.rtlcss.com/bootstrap/v4.0.0/js/bootstrap.min.js" integrity="sha384-54+cucJ4QbVb99v8dcttx/0JRx4FHMmhOWi4W+xrXpKcsKQodCBwAvu3xxkZAwsH" crossorigin="anonymous"></script>

</body>
</html>

exam/templates/exam/category.html
{% extends 'exam/base.html' %}


{% block title %} {{category.title}} {% endblock %}



{% block content %}

    <h2>{{ category.title }}</h2>
  <div class="list-group quiz-list" style=" margin-top: 50px; margin-left: 70px; margin-right: 70px;">
    {% for quiz in quiz_list %}
      <a href="{% url 'exam:question_list' quiz.slug %}" class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{ quiz.title }}</h5>
          <small class="text-muted">{{ quiz.publish }}</small>
        </div>
        <p class="mb-1">{{ quiz.description }}</p>
        <small class="text-muted">طراح آزمون: {{ quiz.author.get_full_name }}</small>
        <small class="text-muted">دسته بندی های آزمون: {{ quiz.category_to_str }}</small>
      </a>
    {% endfor %}
  </div>
{% endblock %}

exam/templates/exam/question_list.html
{% extends 'exam/base.html' %}

{% block title %}{{quiz.title}}{% endblock %}

{% block content %}
  <div class="exam-detail">
    <p class="alert alert-info exam_info" role="alert">{{quiz.title}}</p>

    <form class="" action="{% url 'exam:quiz_result' quiz.slug %}" method="post">{% csrf_token %}
      {% for question in questions %}
      <div class="jumbotron question">
        <p>{{question.title}}</p>
        <input type="radio" id="answer_one" name="{{question.pk}}" value="1">
        <label for="1">{{question.answer_one}}</label><br>
        <input type="radio" id="answer_two" name="{{question.pk}}" value="2">
        <label for="2">{{question.answer_two}}</label><br>
        <input type="radio" id="answer_three" name="{{question.pk}}" value="3">
        <label for="3">{{question.answer_three}}</label><br>
        <input type="radio" id="answer_four" name="{{question.pk}}" value="4">
        <label for="4">{{question.answer_four}}</label>
      </div>
      {% endfor %}
        <div class="btn-exam-submit">
        <input type="submit" class="btn btn-primary" value="پایان آزمون">
      </div>
    </form>
  </div>
{% endblock %}

exam/templates/exam/quiz_list.html
{% extends 'exam/base.html' %}


{% block title %}لیست آزمون ها{% endblock %}

 
{% block content %}
  <div class="list-group quiz-list" style=" margin-top: 50px; margin-left: 70px; margin-right: 70px;">
    {% for quiz in object_list %}
      <a href="{% url 'exam:question_list' quiz.slug %}" class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{ quiz.title }}</h5>
          <small class="text-muted">{{ quiz.publish }}</small>
        </div>
        <p class="mb-1">{{ quiz.description }}</p>
        <small class="text-muted">طراح آزمون: {{ quiz.author.get_full_name }}</small>
        <small class="text-muted">دسته بندی های آزمون: {{ quiz.category_to_str }}</small>
      </a>
    {% endfor %}
  </div>
{% endblock %}

exam/templates/exam/quiz_result.html
{% extends 'exam/base.html' %}

{% block title %}نتیجه آزمون{{quiz.title}}{% endblock %}

{% block content %}
<p class="alert alert-success exam_info" role="alert">شما به تعداد {{number_true_answer}} از {{quiz.count_question_publish}} پاسخ صحیح داده اید.</p>
{% endblock %}